name: Publish NPM Package

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18"
          registry-url: ”https://registry.npmjs.org/“

      - name: Install dependencies
        run: npm install

      - name: Run tests with Karma
        run: npm run test

      - name: Build
        run: npm run build

      - name: Bump version and create tag
        run: |
          git config --global user.name 'isamxus'
          git config --global user.email '834775778@qq.com'
          npm version patch -m "Bump version to %s [skip ci]"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/isamxus/frontend-excelify-test.git
          git push --follow-tags

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
